### set_config
POST http://10.36.79.210:80/connect/api/v1/config HTTP/1.1
content-type: application/json

{
  "profiles": {
    "layer_1_profiles": [
      {"name": "autoneg",    "link_speed": "speed_100_gbps","choice": "autonegotiation"},
      {"name": "manual_RS",  "link_speed": "speed_100_gbps","choice": "manual","manual": {"fec_mode": "reed_solomon"}},
      {"name": "manual_NONE","link_speed": "speed_100_gbps","choice": "manual","manual": {"fec_mode": "none"}}
    ]
  },
  "front_panel_ports": [
      {
        "name": "ixnetwork_port_group_1","choice": "port_group",
        "port_group": {
          "ports": [
            {"front_panel_port": 25,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 26,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 27,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 28,"layer_1_profile_name": "autoneg"}
          ]
        }
      },
      {
        "name": "ixnetwork_port_group_2","choice": "port_group",
        "port_group": {
          "ports": [
            {"front_panel_port": 29,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 30,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 31,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 32,"layer_1_profile_name": "autoneg"}
          ]
        }
      },
      {
        "name": "ixload_port_group_1","choice": "port_group",
        "port_group": {
          "ports": [
            {"front_panel_port":  9,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 11,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 13,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 15,"layer_1_profile_name": "autoneg"}
          ]
        }
      },
      {
        "name": "ixload_port_group_2","choice": "port_group",
        "port_group": {
          "ports": [
            {"front_panel_port": 10,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 12,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 14,"layer_1_profile_name": "autoneg"},
            {"front_panel_port": 16,"layer_1_profile_name": "autoneg"}
          ]
        }
      },
      {"name": "dpu_port_1","choice": "front_panel_port","front_panel_port": {"front_panel_port": 1,"layer_1_profile_name": "manual_NONE"}},
      {"name": "dpu_port_2","choice": "front_panel_port","front_panel_port": {"front_panel_port": 2,"layer_1_profile_name": "manual_NONE"}}
    ],
  "connections": [
    {
      "name": "ARP Bypass 1","functions": [{"choice": "connect_arp","connect_arp": {}}],
      "endpoints": [
        {"choice": "front_panel","front_panel": {"port_name": "ixload_port_group_1","vlan": {"choice": "vlan_range","vlan_range":   {"start":    1,"count": 64}}}},
        {"choice": "front_panel","front_panel": {"port_name": "ixload_port_group_2","vlan": {"choice": "vlan_range","vlan_range":   {"start": 1001,"count": 64}}}}
      ]
    },
    {
      "name": "ARP Bypass 2","functions": [{"choice": "connect_arp","connect_arp": {}}],
      "endpoints": [
        {"choice": "front_panel","front_panel": {"port_name": "ixnetwork_port_group_1","vlan": {"choice": "vlan_range","vlan_range":   {"start":    1,"count": 64}}}},
        {"choice": "front_panel","front_panel": {"port_name": "ixnetwork_port_group_2","vlan": {"choice": "vlan_range","vlan_range":   {"start": 1001,"count": 64}}}}
      ]
    },
    {
      "name": "IxLoad VLAN to DUT VXLAN 1",
      "functions": [
        {
          "choice": "connect_vlan_vxlan",
          "connect_vlan_vxlan": {
            "vxlan_endpoint_settings": {"vni": {"choice": "vni_range","vni_range":  {"start": 1,"count": 64}},"protocols": {"accept": ["tcp"]}},
            "vlan_endpoint_settings": {
              "outgoing_vxlan_header": {
                "src_mac": {"choice": "mac","mac": "80:09:02:01:00:01"},
                "dst_mac": {"choice": "mac","mac": "00:ae:cd:10:7e:c6"},
                "src_ip":  {"choice": "ipv4_range","ipv4_range":  {"start": "221.1.0.1"}},
                "dst_ip": {"choice": "ipv4","ipv4": "221.0.0.1"}
              }
            }
          } 
        }
      ],
      "endpoints": [
        {"choice": "front_panel","front_panel": {"port_name": "ixload_port_group_1","vlan": {"choice": "vlan_range","vlan_range":   {"start": 1,"count": 64}}},"tags": ["vlan"]},
        {"choice": "front_panel","front_panel": {"port_name": "dpu_port_1"},"tags": ["vxlan"]}
      ]
    },
    {
      "name": "IxLoad VLAN to DUT VXLAN 2",
      "functions": [
        {
          "choice": "connect_vlan_vxlan",
          "connect_vlan_vxlan": {
            "vxlan_endpoint_settings": {"vni": {"choice": "vni_range","vni_range":  {"start": 1001,"count": 64}},"protocols": {"accept": ["tcp"]}},
            "vlan_endpoint_settings": {
              "outgoing_vxlan_header": {
                "src_mac": {"choice": "mac","mac": "80:09:02:02:00:01"},
                "dst_mac": {"choice": "mac","mac": "00:ae:cd:10:7e:c6"},
                "src_ip": {"choice": "ipv4_range","ipv4_range":  {"start": "221.2.0.1"}},
                "dst_ip": {"choice": "ipv4","ipv4": "221.0.0.1"}
              }
            }
          }
        }
      ],
      "endpoints": [
        {"choice": "front_panel","front_panel": {"port_name": "ixload_port_group_2","vlan": {"choice": "vlan_range","vlan_range":   {"start": 1001,"count": 64}}},"tags": ["vlan"]},
        {"choice": "front_panel","front_panel": {"port_name": "dpu_port_2"},"tags": ["vxlan"]}
      ]
    },
    {
      "name": "IxNetwork VLAN to DUT VXLAN 1",
      "functions": [
        {
          "choice": "connect_vlan_vxlan",
          "connect_vlan_vxlan": {
            "vxlan_endpoint_settings": {"vni": {"choice": "vni_range","vni_range":  {"start": 1,"count": 64}},"protocols": {"accept": ["udp"]}},
            "vlan_endpoint_settings": {
              "outgoing_vxlan_header": {
                "src_mac": {"choice": "mac","mac": "80:09:02:01:00:01"},
                "dst_mac": {"choice": "mac","mac": "00:ae:cd:10:7e:c6"},
                "src_ip": {"choice": "ipv4_range","ipv4_range":  {"start": "221.1.0.1"}},
                "dst_ip": {"choice": "ipv4","ipv4": "221.0.0.1"}
              }
            }
          }
        }
      ],
      "endpoints": [
        {"choice": "front_panel","front_panel": {"port_name": "ixnetwork_port_group_1","vlan": {"choice": "vlan_range","vlan_range":   {"start": 1,"count": 64}}},"tags": ["vlan"]},
        {"choice": "front_panel","front_panel": {"port_name": "dpu_port_1"},"tags": ["vxlan"]}
      ]
    },
    {
      "name": "IxNetwork VLAN to DUT VXLAN 2",
      "functions": [
        {
          "choice": "connect_vlan_vxlan",
          "connect_vlan_vxlan": {
            "vxlan_endpoint_settings": {"vni": {"choice": "vni_range","vni_range":  {"start": 1001,"count": 64}},"protocols": {"accept": ["udp"]}},
            "vlan_endpoint_settings": {
              "outgoing_vxlan_header": {
                "src_mac": {"choice": "mac","mac": "80:09:02:02:00:01"},
                "dst_mac": {"choice": "mac","mac": "00:ae:cd:10:7e:c6"},
                "src_ip": {"choice": "ipv4_range","ipv4_range":  {"start": "221.2.0.1"}},
                "dst_ip": {"choice": "ipv4","ipv4": "221.0.0.1"}
              }
            }
          }
        }
      ],
      "endpoints": [
        {"choice": "front_panel","front_panel": {"port_name": "ixnetwork_port_group_2","vlan": {"choice": "vlan_range","vlan_range":   {"start": 1001,"count": 64}}},"tags": ["vlan"]},
        {"choice": "front_panel","front_panel": {"port_name": "dpu_port_2"},"tags": ["vxlan"]}
      ]
    },
    {
      "name": "DUT BGP 1",
      "endpoints": [{"choice": "front_panel","front_panel": {"port_name": "dpu_port_1"}},{"choice": "internal","internal": {},"tags": ["bgp_1"]}],
      "functions": [{"choice": "connect_arp","connect_arp": {}},{"choice": "connect_ip","connect_ip": {}}]
    },
    {
      "name": "DUT BGP 2",
      "endpoints": [{"choice": "front_panel","front_panel": {"port_name": "dpu_port_2"}},{"choice": "internal","internal": {},"tags": ["bgp_2"]}],
      "functions": [{"choice": "connect_arp","connect_arp": {}},{"choice": "connect_ip","connect_ip": {}}]
    }
  ]
}

### metrics
#POST https://10.36.79.210:80/connect/api/v1/metrics HTTP/1.1
POST http://10.36.79.210:80/connect/api/v1/metrics/operations/query HTTP/1.1
content-type: application/json

{
"port_metrics":{}
}